### ISSUE TITLE
Error loading: gapit-htmlgraphics-panel

### ISSUE THREAD

**Issue by gcalabro-rli** [gapitio/gapit-htmlgraphics-panel#87] opened 2022-02-06 19:07 UTC
**What happened**:
Installed the plugin via CLI. Went to add a new panel and selected the HTML panel. The error in the preview immediately shows: "Error loading: gapit-htmlgraphics-panel". The properties pane shows none of the expected settings either.
**What you expected to happen**:
Expected the panel to load with defaults.
**How to reproduce it (as minimally and precisely as possible)**:
Install it via CLI on Grafana Enterprise v8.3.4
Create new dashboard
Add new panel
Select Html
**Anything else we need to know?**:
Using Grafana Enterprise is that maybe not supported?
**Environment**:
K8, Linux
- Grafana version: Enterprise v8.3.4
- Plugin (gapit-htmlgraphics-panel) version: 2.0.1

**Comment by flesa** [comment] 2022-02-07 07:37
Hello @gcalabro-rli 

This issue is known and should be resolved with gapit-htmlgraphics-panel version: 2.0.2. This version is on its way but grafana has yet to release it.
For now the issue should be resolved by going back to Grafana version: v8.3.3 or await the release of 2.0.2

**Comment by sbgap** [comment] 2022-02-07 07:59
Duplicate of #78

**Comment by tillsteinbach** [comment] 2022-02-10 16:54
Have the same issue and going back to 8.3.3 is not an option. Is there an estimate how long it could take for 2.0.2 to arrive?

**Comment by ZuperZee** [comment] 2022-02-11 13:07
You could download it from github with ```grafana-cli --pluginUrl https://github.com/gapitio/gapit-htmlgraphics-panel/releases/download/v2.0.2/gapit-htmlgraphics-panel-2.0.2.zip plugins install gapit-htmlgraphics-panel```

**Comment by ZuperZee** [comment] 2022-02-11 22:17
Closing as this is fixed in the new release (hopefully). If the issue persists in the new release, please open a new issue.

**Closed by ZuperZee** 2022-02-11 22:17 UTC
Labels: bug, duplicate
